### ISSUE TITLE
Json Depth Issue - Found the fix

### ISSUE THREAD

**Issue by mmccollum2** [lwhitelock/Pax8API#1]
Hey! We love your module so far, noticed that the Pax8 API has different requirements and isn't working properly with your module in the Invoke-Pax8Request.ps1 for ConvertFrom-Json -Depth 100 as it doesn't accept the Depth, when it's removed, it seems to work.

**Comment by mmccollum2** [comment]
Turns out this feature was added in Powershell 6.2 and not in 5.1
Adding for others to find out if needed too! Thanks!

**Comment by lwhitelock** [comment]
It shouldn't be needed on ConvertFrom-Json so I've removed it and pushed an update.
